version: '3.4'

services:
  transactions:
    image: transactions
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    container_name: "transactions-api"
    depends_on: 
      - postgres
